### ISSUE TITLE
Using this to add support for jsctags in gutentags

### ISSUE THREAD

**Issue by marlun** [tkonolige/ctags-shim#1]
Hi, I don't know anything about Haskell but I would love to use this to add support for jsctags into gutentags as discussed in https://github.com/ludovicchabant/vim-gutentags/issues/95 but I've got no idea how to do it from your README. 😄

**Comment by tkonolige** [comment]
Under the `executables` section in the `~/.ctags-shim.yaml` you need to add the following:

```yaml
  - jsctags
    flags:
      - "-f"
    extensions:
      - js
```

Could you clarify what was confusing about the README?
